testing v4 artifact
oss-slu/SpeechTranscription pull request #161
Opened 2024-09-24 21:25 UTC by sagar3181

Fixes #issue_number

**What was changed?**

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*

**Why was it changed?**

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*

**How was it changed?**

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

**Screenshots that show the changes (if applicable):**

2024-09-25 23:36 UTC, kate-holdener commented
Please provide details in this PR description. Also, as @kungfuchicken  suggested, it may be better to move each of builds for windows/mac os to separate workflows so it’s clear when one of them is failing, and it can get fixed quickly.

2024-09-25 23:37 UTC, kate-holdener commented
You'll also want to force this workflow to run on this branch, to test the outcome.

2024-09-26 01:55 UTC, kate-holdener commented
Please test the workflow by forcing it to run on the testingv4artifact branch.

2024-09-26 01:56 UTC, kate-holdener commented on .github/workflows/create-executable.yml
>          os: ["windows-latest", "macos-latest"]
Try splitting it into two workflow files, one for windows and one for mac.

2024-09-26 01:57 UTC, kate-holdener commented on .github/workflows/create-executable.yml
>          os: ["windows-latest", "macos-latest"]
Also, when splitting into two workflows, remove continue-on-error: true from the configuration

2024-09-26 01:57 UTC, kate-holdener commented on .github/workflows/create-executable.yml
> +          fi
Once you split this into two workflows, this can be removed

2024-09-27 13:51 UTC, kate-holdener commented on .github/workflows/macos-build.yml
> +            exit 1
Since you removed continue on error, you don't need this.
```suggestion
```

2024-09-27 13:51 UTC, kate-holdener commented on .github/workflows/windows-build.yml
> +            exit 1
Since you removed continue on error, you don't need this
```suggestion

```

2024-09-27 13:52 UTC, kate-holdener commented on .github/workflows/macos-build.yml
> +      - fix-mac-exe
Let's add testingv4artifact branch to the list of branches on which to run this workflow (for now), to test the workflow.
```suggestion
      - fix-mac-exe
      - testingv4artifact
```

2024-09-27 13:59 UTC, kate-holdener commented
The workflow ran successfully, but there was the following warning:
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/. To be fair, the same warning happens on the pylint workflow.

2024-09-27 14:02 UTC, kate-holdener commented on .github/workflows/windows-build.yml
>        - fix-exe
Let's temporarily add testingv4artifact branch to the workflow, to test it.
```suggestion
      - fix-exe
      - testingv4artifact
```

2024-09-27 14:35 UTC, kate-holdener commented
Windows build has been running for 30 minutes, and I don't think it will terminate. I'll let it go a bit longer.

2024-10-03 18:54 UTC, kungfuchicken requested changes
Windows build is still failing: https://github.com/oss-slu/SpeechTranscription/actions/runs/11110615648 @emrameduseljac and @sagar3181 i will be on campus on Friday and Monday. If you want to meet to work on this together we can coordinate a specific time on Slack.

2024-10-21 15:38 UTC, merged