Unit Testing For Button Responsiveness
oss-slu/SpeechTranscription pull request #165
Opened 2024-09-30 18:38 UTC by emrameduseljac

Fixes #160 

I added unit tests to test button responsiveness of the upload/record buttons in a new file: test_gui.py. This file is under the tests/ directory.

This was added because the responsiveness issue with button-clicking was identified as being dependent on the Python version. Issues with buttons responding either very slowly or not at all was occurring on machines with a Python version older than 3.11.7. When upgrading to a Python version that is 3.11.7 or greater, the button responded as expected. By adding these tests, we can confirm that the buttons perform correctly when the application is being run in Python 3.11.7 or higher.

Created tests:
* invoke_upload_button_and_measure_time()
* invoke_record_button_and_measure_time()
* Implemented mocks for uploadAudio and recordAudio methods

2024-10-01 18:22 UTC, kpothuganti commented on tests/test_gui.py
> +
can include a comment of the export command needed in order to run the tests (or add the path line to this file)

2024-10-01 18:28 UTC, kpothuganti requested changes
add the path statement(s) to the file:

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

or mention the export command needed to run the tests, in a comment:
export PYTHONPATH=$(pwd)

2024-10-01 19:13 UTC, kate-holdener commented on tests/test_gui.py
Unit tests that rely on "time" are not a good idea. Instead, you want to set up a test that asserts for whether a function associated with your button has been called. You would use 'mock' functions for that: specifying that instead of the real function associated with a given button, use a mock. There is a way to check if a mock function has been called or not

2024-10-01 19:14 UTC, kate-holdener commented on tests/test_gui.py
> +@pytest.mark.skipif(sys.version_info >= (3, 11, 7), reason="Only run on Python versions before 3.11.7")
Let's not do the 'skip' part. Just add your test cases. Run them on a 'broken' python version and see if they fail for the right reason. Then run them on the working python version and they should pass. This way, if someone uses a broken python version, the tests will fail for that person.

2024-10-07 21:27 UTC, sagar3181 requested changes

2024-10-07 21:27 UTC, sagar3181 commented on tests/test_gui.py
> +import pytest
Add a comment for "pip install pytest-mock"

2024-10-08 04:28 UTC, sagar3181 approved these changes
Looks good for the merge!

2024-10-08 04:38 UTC, merged