WIP on Issue #96
oss-slu/SpeechTranscription pull request #98
Opened 2023-11-13 21:47 UTC by TravisHerrick7

Fixes #96 

**What was changed?**
Nothing was "changed", I created a new .txt file that has the installation steps for the nltk library for MacOS. I will do this for Windows and Linux after interviewing those who have done it.

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I created a new documentation file titled nltk-installation-guide.txt that contains the guide for installing nltk.

**Why was it changed?**
This was created because the nltk library was giving everyone issues who has tried to develop on this project and there was no documentation for this very troubling issue that is not intuitive to solve. Therefore, I created documentation for future developers to look at so that they can avoid this hassle.

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
I am fixing the issue of there being no guide for installing nltk on every OS, as my file will have a guide for each OS to install nltk.

**How was it changed?**
Creating a new .txt file with the guide to download nltk on each OS.

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
I created a new file nltk-installation-guide.txt and the important lines are dependent on which OS you use as that section will contain the guide to installing it on your OS.

**Screenshots that show the changes (if applicable):**
N/A

2023-11-14 22:37 UTC, kate-holdener requested changes
@TravisHerrick7 Looks like you accidentally deleted a lot of important files. Please undo the delete. @loganwyas FYI

2023-11-14 22:38 UTC, kate-holdener submitted a review, later dismissed

2023-11-14 22:38 UTC, kate-holdener commented on nltk-installation-guide.txt
I suggest making this a .md file (instead of .txt)

2023-11-14 22:58 UTC, TravisHerrick7 commented
> @TravisHerrick7 Looks like you accidentally deleted a lot of important files. Please undo the delete. @loganwyas FYI

@kate-holdener Sounds good. I will look into this.

2023-11-19 16:07 UTC, loganwyas commented
@TravisHerrick7 How close is this to being completed?

2023-11-19 23:19 UTC, TravisHerrick7 commented
> @TravisHerrick7 How close is this to being completed?

Fairly close. I haven't completed it yet as I was out of town this weekend and have been working today. I will get this ready to merge tonight.

2023-11-20 19:52 UTC, loganwyas approved these changes

2023-11-20 19:53 UTC, merged